#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KaamelottSampler.Resource", IsApplication=true)]

namespace KaamelottSampler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::KaamelottSampler.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::KaamelottSampler.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::KaamelottSampler.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::KaamelottSampler.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::KaamelottSampler.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::KaamelottSampler.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::KaamelottSampler.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::KaamelottSampler.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::KaamelottSampler.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::KaamelottSampler.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::KaamelottSampler.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::KaamelottSampler.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::KaamelottSampler.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::KaamelottSampler.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::KaamelottSampler.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::KaamelottSampler.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::KaamelottSampler.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::KaamelottSampler.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::KaamelottSampler.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::KaamelottSampler.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::KaamelottSampler.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::KaamelottSampler.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::KaamelottSampler.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::KaamelottSampler.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::KaamelottSampler.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::KaamelottSampler.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int angharad = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arthur = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int arthurleroiburgonde = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int attila = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bohort = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int breccan = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int caius = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dagonet = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int demetra = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int elias = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int eliasdekelliwich = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int guenievre = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int guethenoc = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_errorstatus = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_play_black = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_play_white = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_share_black = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_share_white = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_successstatus = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int kadoc = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int karadoc = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ladamedulac = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int lancelot = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int lemaitredarmes = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int leodagan = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int lerepurgateur = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int letavernier = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int levequeboniface = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int linterprete = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int logo_large = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int merlin = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int perceval = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int profile_generic = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int roparzh = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ropharz = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int roundedbg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int roundedbgdark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int search = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int seli = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int slideout = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int venec = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int yvain = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int Imageview_character = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Text = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int Textview_Episode = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int Textview_Title = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int loadingImage = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int loadingProgressBar = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int loadingProgressWheel = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int main_editText_search = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int main_listView_Samples = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int textViewStatus = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MyCustomRow = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
